### ISSUE TITLE
cc!removeinfractions sometimes crashes with a TypeError on incorrect infraction number on upgrade-to-v13 branch

### ISSUE THREAD

**Issue by mikejoh12** [CodecademyCommunity/codecademy-discord-bot#266]
## Describe the bug
cc!removeinfractions sometimes crashes with a TypeError on incorrect infraction number. Error msg:

TypeError: Cannot read properties of undefined (reading 'user')
    at Query.<anonymous> (/home/mikejoh12/projects/codecademy-discord-bot/commands/utility/removeinfraction.js:60:21)
    at Query.<anonymous> (/home/mikejoh12/projects/codecademy-discord-bot/node_modules/mysql/lib/Connection.js:526:10)
    at Query._callback (/home/mikejoh12/projects/codecademy-discord-bot/node_modules/mysql/lib/Connection.js:488:16)
    at Query.Sequence.end (/home/mikejoh12/projects/codecademy-discord-bot/node_modules/mysql/lib/protocol/sequences/Sequence.js:83:24)
    at Query._handleFinalResultPacket (/home/mikejoh12/projects/codecademy-discord-bot/node_modules/mysql/lib/protocol/sequences/Query.js:149:8)
    at Query.EofPacket (/home/mikejoh12/projects/codecademy-discord-bot/node_modules/mysql/lib/protocol/sequences/Query.js:133:8)
    at Protocol._parsePacket (/home/mikejoh12/projects/codecademy-discord-bot/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/home/mikejoh12/projects/codecademy-discord-bot/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/home/mikejoh12/projects/codecademy-discord-bot/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/home/mikejoh12/projects/codecademy-discord-bot/node_modules/mysql/lib/protocol/Protocol.js:38:16)
[nodemon] app crashed - waiting for file changes before starting...

## Expected behavior
No TypeError crash should occur.

## Additional context
Seems like this bug was present prior to the v13 port.

**Comment by lyallstewart** [comment]
Closed by #269
